// One butterfly stage of a Cooley-Tukey inverse FFT, applied to two independent
// complex signals packed in .rg and .ba.
//
// The schedule comes from a precomputed table generated by ButterflyPlan on the
// CPU: texel (stage, lane) holds (twiddle.re, twiddle.im, indexA, indexB). Every
// lane performs the same unbranched operation, out = a + w*b, because a lane in
// the subtracting wing of a butterfly carries a twiddle that is already half a
// turn further round the unit circle. Stage 0's indices are bit-reversed, which
// folds the reordering into the first pass.

#pragma include "lib_complex.glsl"

in vec2 v_uv;
out vec4 fragColor;

uniform sampler2D u_source;
uniform sampler2D u_butterfly;   // log2(N) wide, N tall
uniform int u_stage;
uniform int u_horizontal;        // 1 for the row pass, 0 for the column pass

void main() {
    ivec2 texel = ivec2(gl_FragCoord.xy);
    int lane = u_horizontal == 1 ? texel.x : texel.y;

    vec4 plan = texelFetch(u_butterfly, ivec2(u_stage, lane), 0);
    vec2 twiddle = plan.xy;
    int indexA = int(plan.z);
    int indexB = int(plan.w);

    ivec2 coordA = u_horizontal == 1 ? ivec2(indexA, texel.y) : ivec2(texel.x, indexA);
    ivec2 coordB = u_horizontal == 1 ? ivec2(indexB, texel.y) : ivec2(texel.x, indexB);

    vec4 a = texelFetch(u_source, coordA, 0);
    vec4 b = texelFetch(u_source, coordB, 0);

    fragColor = vec4(a.rg + cmul(twiddle, b.rg),
                     a.ba + cmul(twiddle, b.ba));
}
