package com.bluemeridian.core.tools;

import com.bluemeridian.core.boat.BoatMesh;
import com.bluemeridian.core.boat.HullLoft;
import java.io.PrintStream;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.Base64;
import java.util.Locale;

/**
 * Writes the hull as a JavaScript module for the browser build.
 *
 * <p>The hull is generated by six hundred lines of curve evaluation in
 * {@link HullLoft}, and it is entirely static: the same vertices every run. Hand
 * transliterating that into JavaScript, as the spectrum and the sailing model are,
 * would be six hundred lines of duplicated geometry kept in step by a checksum -
 * all of the cost of a second implementation and none of the benefit, because
 * unlike the physics there is nothing here a server needs to reason about
 * independently.
 *
 * <p>So it is baked instead. One definition, one set of vertices, no drift
 * possible. The sails are <em>not</em> baked, because they are rebuilt every time
 * the sheet moves and the browser has to be able to do that itself.
 *
 * <p>Arrays go out as base64 of their little-endian bytes rather than as JSON
 * numbers. A hull of this size is about 120 KB that way and closer to 700 KB as
 * decimal text, and the page is meant to open over a phone connection.
 */
public final class BoatMeshDump {

    private BoatMeshDump() {
    }

    public static void main(String[] args) {
        BoatMesh hull = HullLoft.class40().hull();
        PrintStream out = System.out;

        out.println("// GENERATED by ./gradlew :core:generateWebBoat - do not edit.");
        out.println("//");
        out.println("// The hull, deck, coachroof, appendages, standing rig and deck gear, as");
        out.println("// generated by HullLoft in `core`. Baked rather than transliterated: the");
        out.println("// geometry is static, so a second implementation would be six hundred lines");
        out.println("// of duplication kept in step by a checksum, with nothing gained. The sails");
        out.println("// are still built in the browser, because they move.");
        out.println("//");
        out.printf(Locale.ROOT, "// %d vertices, %d triangles.%n",
                hull.vertexCount(), hull.triangleCount());
        out.println();
        out.println("const decode = (text, Type) => {");
        out.println("  const binary = atob(text);");
        out.println("  const bytes = new Uint8Array(binary.length);");
        out.println("  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);");
        out.println("  return new Type(bytes.buffer);");
        out.println("};");
        out.println();
        out.println("export const HULL_MESH = {");
        emitFloats(out, "positions", hull.positions);
        emitFloats(out, "normals", hull.normals);
        emitFloats(out, "materials", hull.materials);
        emitFloats(out, "uvs", hull.uvs);
        emitIndices(out, hull.indices);
        out.println("};");
    }

    private static void emitFloats(PrintStream out, String name, float[] values) {
        ByteBuffer buffer = ByteBuffer.allocate(values.length * 4).order(ByteOrder.LITTLE_ENDIAN);
        for (float v : values) {
            buffer.putFloat(v);
        }
        out.printf(Locale.ROOT, "  %s: decode('%s', Float32Array),%n",
                name, Base64.getEncoder().encodeToString(buffer.array()));
    }

    private static void emitIndices(PrintStream out, int[] values) {
        // 16-bit while the mesh fits, which it comfortably does, and 32-bit if it
        // ever stops fitting rather than wrapping silently into garbage.
        int max = 0;
        for (int v : values) {
            max = Math.max(max, v);
        }
        boolean wide = max > 65535;
        ByteBuffer buffer = ByteBuffer.allocate(values.length * (wide ? 4 : 2))
                .order(ByteOrder.LITTLE_ENDIAN);
        for (int v : values) {
            if (wide) {
                buffer.putInt(v);
            } else {
                buffer.putShort((short) v);
            }
        }
        out.printf(Locale.ROOT, "  indices: decode('%s', %s),%n",
                Base64.getEncoder().encodeToString(buffer.array()),
                wide ? "Uint32Array" : "Uint16Array");
    }
}
