package com.bluemeridian.core.ocean.spectrum;

import com.bluemeridian.core.math.Mth;

/**
 * Narrow-band swell: a Gaussian in angular frequency carrying a prescribed
 * significant wave height.
 *
 * <pre>
 *   S(w) = (Hs^2 / 16) / (sigma * sqrt(2*pi)) * exp( -(w - wp)^2 / (2*sigma^2) )
 * </pre>
 *
 * <p>Swell is modelled separately from the wind sea and added to it, rather than
 * being folded into one spectrum, because the two are physically independent:
 * swell was generated by a storm somewhere else, days ago, and its direction has
 * nothing to do with the breeze on your face. Getting a long Atlantic swell
 * running under a local sea-breeze chop from a different quarter is most of what
 * makes an ocean read as an ocean rather than as a wind tunnel.
 */
public final class GaussianSwellSpectrum implements WaveSpectrum {

    private final double peakOmega;
    private final double sigma;
    private final double m0;

    /**
     * @param significantHeight swell Hs in metres
     * @param peakPeriod        swell peak period Tp in seconds
     * @param narrowness        fractional bandwidth: sigma = narrowness * wp.
     *                          0.05-0.10 is a clean, well-sorted ocean swell.
     */
    public GaussianSwellSpectrum(double significantHeight, double peakPeriod, double narrowness) {
        if (peakPeriod <= 0.0) {
            throw new IllegalArgumentException("swell period must be positive, got " + peakPeriod);
        }
        if (narrowness <= 0.0) {
            throw new IllegalArgumentException("narrowness must be positive, got " + narrowness);
        }
        this.peakOmega = Mth.TAU / peakPeriod;
        this.sigma = narrowness * peakOmega;
        this.m0 = significantHeight * significantHeight / 16.0;
    }

    @Override
    public double energy(double omega) {
        if (omega <= 1e-6) {
            return 0.0;
        }
        double d = omega - peakOmega;
        return m0 / (sigma * Math.sqrt(Mth.TAU)) * Math.exp(-(d * d) / (2.0 * sigma * sigma));
    }

    @Override
    public double peakOmega() {
        return peakOmega;
    }

    @Override
    public double zerothMoment() {
        return m0;
    }
}
